require "neumnotele_config.plugin_config.colorscheme_config"
require "neumnotele_config.plugin_config.lualine"
require "neumnotele_config.plugin_config.telescope"
require "neumnotele_config.plugin_config.treesitter"
require "neumnotele_config.plugin_config.lsp_config"
require "neumnotele_config.plugin_config.autocompletions"
require "neumnotele_config.plugin_config.fugitive"
require "neumnotele_config.plugin_config.gitsigns"
require "neumnotele_config.plugin_config.git-worktree"
require "neumnotele_config.plugin_config.nvim-tree"
require "neumnotele_config.plugin_config.todo-comments"
require "neumnotele_config.plugin_config.marks"
require "neumnotele_config.plugin_config.treesitter-context"
-- require "neumnotele_config.plugin_config.bufferline"
require "neumnotele_config.plugin_config.barbar"
require "neumnotele_config.plugin_config.harpoon"
